Output docs/img/cover.gif

Set Theme "Catppuccin Mocha"
Set Shell "pwsh"
Set FontSize 32
Set Width 1200
Set Height 600
Set Padding 40
Set WindowBar Fixed
Set WindowBarSize 60
Set Margin 20
Set MarginFill "#8839ef"
Set BorderRadius 10

Type "jack --help"
Sleep 500ms
Enter
Sleep 2s

Type "jack uuid generate"
Sleep 500ms
Enter
Sleep 1s

Type "jack timestamp"
Sleep 500ms
Enter
Sleep 1s

Type "jack lorem --count 10"
Sleep 500ms
Enter
Sleep 2s
