Output docs/img/jwt.gif

Set Theme "Catppuccin Mocha"
Set Shell "pwsh"
Set FontSize 32
Set Width 1200
Set Height 500
Set Padding 40
Set WindowBar Fixed
Set Margin 20
Set MarginFill "#8839ef"
Set BorderRadius 10

Type "jack jwt 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'"
Sleep 500ms
Enter
Sleep 3s
